### ISSUE TITLE
`Ops.S7_object`  containing `%*%`

### ISSUE THREAD

**Issue by mmaechler** [RConsortium/S7#321]
Related to #320, I was exploring and found that indeed, dispatch for arithmetic happens with group method for `Ops` :
```
S7:::Ops.S7_object
function (e1, e2) 
{
    base_ops[[.Generic]](e1, e2)
}
<bytecode: 0x80a7f08>
<environment: namespace:S7>
```
and indeed, as mentioned in #320   the `base_ops` involved here are somewhat not initialized (anymore ?) and just empty.
**HOWEVER**  there is more:   The S7 `base_ops`  do contain `%*%`  but really really should NOT.

It seems clear this is currently explicitly "desired" --- probably because we don't want `S7` to depend on R 4.3.0 yet, and hence keep the code simple enough...
     https://github.com/RConsortium/OOP-WG/blame/main/R/zzz.R#L105
but it is really "wrong" and in contrast with base R's documentation of  group generics (`?groupGenerics`) which explains that `"matrixOps"` is a separate group generic.

**Comment by mmaechler** [comment]
Also, the "signature" of `%*%`  is  `(x,y)`,  not `(e1,e2)`   and that's also the case for `crossprod()` and `tcrossprod()` which should become  "matrixOps"  eventually, too.

But yes, this can wait, e.g. for release of R 4.4.x

**Comment by mmaechler** [comment]
I have spent more thinking on this:  I've come the stage of claiming that the whole idea of making `%*%`   a group generic at all was flawed, and only adds unnecessary complications; notably also for R itself. 
My current pretty strong opinion is that R core should abolish the (new in R 4.3.x) `"matrixOps"` group generic, and S7 should also make  `%*%` a  normal 2-argument generic function.
If it can be dealt with as part of a group generic, it can also be dealt with on its own.
I think extra group generic (`"matrixOps"`) just complicates everything and has no benefit or almost no benefit in the case we would add `"crossprod"` and `"tcrossprod"` to it.

**Comment by t-kalinowski** [comment]
If I recall correctly, the original motivation for adding the matrixOps group was partially motivated by economy - the Ops Group generic is the only S3 dispatch mechanism that allows a function to dispatch on the 2nd argument. Wanting to make `%*%` work with S7 (meaning, S3),
we were faced with the choice between making 2-argument dispatch generally available to functions outside of the Ops Group, or extending the Ops group to include a new member. 

(For reference, here is a link to some of the previous discussions: https://bugs.r-project.org/show_bug.cgi?id=18483)

I would be happy work on making 2-argument S3 dispatch available to regular, non-Ops functions, and migrating `%*%` to the new approach.

However, before we embark on that path: the need for such a "generic" mechanism is I think diminished with the release of S7. Any R user wanted to defined an operator that performs 2-argument dispatch can now use S7 to achieve that goal:
``` r
library(S7)

`%xyz%` <- new_generic("%xyz%", c("x", "y"))

method(`%xyz%`, list(class_double, class_any)) <- 
method(`%xyz%`, list(class_any, class_double)) <- function(x, y) "woof"

"abc" %xyz% 1
#> [1] "woof"
1 %xyz% "abc"
#> [1] "woof"
```

This approach however was not available for `` base::`%*%` ``, because it was not compatible with S7/S3. In light of this, one way to think of the `matrixOps` addition is as a narrow backwards and forwards compatible patch that adds multiple dispatch to functions already defined in R, with the understanding that this is not a generally prefered approach and that any new functions requiring multiple dispatch should use S7 to achieve that goal.

**Comment by t-kalinowski** [comment]
> Do you mean this would need to happen in base R .. or is this only needed "inside" S7?

My understanding is that this would need to happen in base R, but I readily admit I might not have the full picture. 

Now that `%*%` performs S3 dispatch, it is already in code out there. For example, reticulate exports a [`%*%` method](https://github.com/rstudio/reticulate/blob/9f86183fc3c27f7fab3d5fcce6b31d525bcf7fcd/NAMESPACE#L12), making usages of `%*%` like in [this blog post](https://blogs.rstudio.com/ai/posts/2023-05-25-llama-tensorflow-keras/) possible. Also, a few SO questions come up on this topic, like [this one](https://stackoverflow.com/questions/75893991/how-can-i-write-a-method-for-a-base-matrix-s3-subclass/75894209#75894209)

I think if we get rid of the "matrixOps" group it's OK, but removing 2 argument S3 dispatch from `%*%` will be a breaking change for many people. How to do so without any changes in base R I don't see. The approach of coding up a "manual" version of 2 argument dispatch with `if(is...(x) && is...(y)) { ....}` in `do_matmul()` in R C sources seems to me the most feasible approach.

**Comment by mmaechler** [comment]
Yes,  now I also am aware of more: It *is* in base, and per your/our "minimal patch strategy" (change as little as possible)
you had seen back then that for internal generics, there is only 2-argument dispatch via (C level) `DispatchGroup()` and so we had decided to go via `DispatchGroup()`  ... but I now remember, that even back then you/I/we became aware of the fact that this 2-argument-dispatch part of  `DispatchGroup()` was not really large and also not much entangled with group-dispatch but just with general (C-level) dispatch. ... i.e. *could* have been factored out (or _copied_ instead if we'd be lazy and did not care for DRY) and used or reused from something like `DispatchOrEval_2arg()`.

I was not proposing to *stop* having `%*%` generic *but* to do that via the new artificial group  "matrixOps".

And that's still what I think would keep things much nicer and transparent:
Create something like  `DispatchOrEval_2arg()`  {not that name probably}   and then call  *that* instead of `DispatchGroup()` in base R's  do_matprod() procedure...

**Comment by t-kalinowski** [comment]
Coming back to this after two days of this topic in the back of my mind. 

I agree that adding the "matrixOps" group is perhaps not a clean-room ideal design, but on the whole, I like the solution we settled on. It works well, is elegant in its minimalism, and doesn't get in anyones way. The work involved to revisit this design will not be trivial, and, if I'm understanding, the benefits would be mostly aesthetic for those like us working on the internals. Most everyone else is able to ignore the fact that the "matrixOps" group exists. I like the idea of adding `crossprod()` and `tcrossprod()` too.

The capability of 2 argument dispatch is generally available in R with S7 now, and life is finite. For example, I'd much rather focus our time and energy on https://github.com/RConsortium/OOP-WG/issues/298.
